### ISSUE TITLE
Issue with Permata Virtual Account

### ISSUE THREAD

**Issue by aganrian** [Midtrans/midtrans-java#14]
Hi i already use SDK for Java
Why when im using for Permata Bank Account 
always return 408 when call api from my source code..

this is sample input : 
{"customer_details":{"first_name":"","last_name":"","email":"","phoneNumber":""},"payment_type":"permata","custom_expiry":{"order_time":"2021-09-30 20:55:46 +0700","expiry_duration":"1","unit":"hour"},"transaction_details":{"order_id":"XXXXXXX21094510121276159334997000002","gross_amount":"950000"}} 

can u explain what to do?

**Comment by Xaxxis** [comment]
Hi @aganrian Thank you for reaching out to us

Does this happen on Production or Sandbox?

Thank you

**Comment by aganrian** [comment]
hi @Xaxxis this happen in sandbox... im using SDK java. and my project write in JAVA Spring Boot.
any issue with utf-8 or body or not.. but when im using postman that sample input work perfectly..
im confused with that

**Comment by Xaxxis** [comment]
Hi @aganrian in specific payment channels. our server can't parse charset=utf8, We already info our team for this one. I Will hotfix the library and get back to you with an update. 

Thank you

**Comment by aganrian** [comment]
Hi @Xaxxis oke thx u. for support. i will waiting for updates

**Comment by Xaxxis** [comment]
Hi @aganrian the fix was released ya, please kindly update your library using the latest version v3.1.2

Thank You

**Comment by aganrian** [comment]
hi broo okee thx u.. for support @Xaxxis

**Comment by aganrian** [comment]
hi @Xaxxis i already using version 3.1.2 but same error with permata account 
please see my attachement log
![image](https://user-images.githubusercontent.com/3069140/135608476-835aaa6e-c771-420c-99fb-e03d35447570.png)

i also check APIHTTPClient.class
have changes with update 3.1.2
![image](https://user-images.githubusercontent.com/3069140/135608394-663fc739-6cbd-41cf-af63-b88f93752b89.png)

**Comment by aganrian** [comment]
hi @Xaxxis this case was solved i'm already changes manually. thx u bro
