### ISSUE TITLE
issus with mandiri Bill

### ISSUE THREAD

**Issue by onlyandri** [Midtrans/midtrans-java#16]
Hi i already use SDK for Java
Why when im using for Mandiri Bill
it always return {"status_code":"400","status_message":"One or more parameters in the payload is invalid.","validation_messages":["echannel is required"],"id":"xxx-x-4xxf97-900f-xxxx"}

can you explain what happen  for this error ?

**Comment by Xaxxis** [comment]
Hi @onlyandri thank you for reaching out to us
The error validation above happens cause the body request missing `echannel` JSON object. You need to add the echannel object from your request body.

```
{
    "payment_type": "echannel",
    "transaction_details": {
        "gross_amount": 44000,
        "order_id": "order-101d-test"
    },
    "echannel" : {
        "bill_info1" : "Payment For:",
        "bill_info2" : "Food"
    }
}
```
https://api-docs.midtrans.com/#mandiri-bill-payment

Thank you

**Comment by Xaxxis** [comment]
Closed due to inactivity, if the issue persists or you have other general questions, please reach us via email at support@midtrans.com

Thank you
