### ISSUE TITLE
X-Override-Notification is not Thread Safe

### ISSUE THREAD

**Issue by khannedy** [Midtrans/midtrans-java#17]
We have problem because X-Override-Notification is set globally in config

https://github.com/Midtrans/midtrans-java#override-notification-url

We need to set X-Override-Notification per http request, not globally, because the url is different in every transaction

**Comment by Xaxxis** [comment]
Hi Mas @khannedy thanks for asking.

Do you still can't set paymentOverrideNotification via apiConfig Mas? it can set dynamically via setter `paymentOverrideNotification`

sample:
```java
// make the config via builder
Config configOptions = Config.builder()
            .enableLog(true)
            .setIsProduction(isProduction)
            .setServerKey(sandboxServerKey)
            .setClientKey(sandboxClientKey)
            .build();

// set config to MidtransCoreApi object
MidtransCoreApi coreApi = new ConfigFactory(configOptions).getCoreApi();

// set override notif dynamically via apiConfig on coreApi object, before request charge
coreApi.apiConfig().paymentOverrideNotification("http://midtrans-java.herokuapp.com/notif/append1");

// then do the request charge
JSONObject object = coreApi.chargeTransaction(body);
```

**Comment by Xaxxis** [comment]
Hi, Mas @khannedy could you help to confirm, is our suggestion above valid?

**Comment by khannedy** [comment]
I want to change different endpoint every time I do charge transaction

for example : http://midtrans-java.herokuapp.com/notif/{orderId}

{orderId} is dynamic per transaction

If I need to change the apiConfig() every time I want to do charge transaction, it will get race condition if in the same time, I call change it

```
coreApi.apiConfig().paymentOverrideNotification("http://midtrans-java.herokuapp.com/notif/1");
```

because apiConfig() is global and singleton

**Comment by khannedy** [comment]
it should have feature to send notif URL without change apiConfig(), for example : 

```
coreApi.chargeTransaction(body, notifUrl);
```

**Comment by Xaxxis** [comment]
Hi Mas @khannedy thanks for the response and suggestion. So the issue will happens in the race condition. Will check further on this

**Comment by Xaxxis** [comment]
Hi Mas @khannedy after testing using the concurrent test in Junit. This does not happen when using our static method and param config on this [method](https://github.com/Midtrans/midtrans-java/blob/master/library/src/main/java/com/midtrans/httpclient/CoreApi.java#L95). So the config object can be used by HTTP client class on the charge method in param. Thank you 

The testing unit will be pushed on the next release ya Mas

We test the implementation like this:
```
Timestamp timestamp = new Timestamp(System.currentTimeMillis());
private final static String WEBHOOK_ENDPOINT = "https://example.com";

public void firstRequest() throws Exception {
   String orderId = "CONCURRENT-TEST-1-" +timestamp.getTime();
   
   Config configOptions1 = Config.builder()
        .setServerKey(mainServerKey)
        .setPaymentOverrideNotification(WEBHOOK_ENDPOINT + "?id=" + orderId)
        .build();

   JSONObject result = CoreApi.chargeTransaction(<Request_body>, configOptions1);
}

public void secondRequest() throws Exception {
     String orderId = "CONCURRENT-TEST-2-" +timestamp.getTime();
     
     Config configOptions2 = Config.builder()
         .setServerKey(secondServerKey)
         .setPaymentOverrideNotification(WEBHOOK_ENDPOINT + "?id=" + orderId)
         .build();
     
     JSONObject result = CoreApi.chargeTransaction(<Request_body>, configOptions2);
}
```

**Comment by Xaxxis** [comment]
No response from the author, If any another questions, please contact us [here](https://midtrans.com/id/contact-us)

Thank you
