### ISSUE TITLE
Wrong Line on Notification Example

### ISSUE THREAD

**Issue by rizkyandriawan** [Midtrans/midtrans-java#5]
In the example on your readme.md and your example code, you write something like this:

`if (fraudStatus.equals("capture")) {
            if (fraudStatus.equals("challenge")) {

            } else if (fraudStatus.equals("accept")){

            }
        } `

which makes no sense, because a map can't have 2 values of 'fraud_status' at once.

so I recheck and compare with your Node and PHP example and it turned out the first line is supposed to be 

`transactionStatus.equals("capture")`

**Comment by Xaxxis** [comment]
Hi @rizkyandriawan , 

We has already fixed regarding the issue. Thank you for your contribution  :+1:

**Comment by rizkyandriawan** [comment]
ggwp, thanks for the fast response :D
