### ISSUE TITLE
Connection Pooling Support

### ISSUE THREAD

**Issue by rickzal13** [Midtrans/midtrans-java#6]
please add Connection Pooling Support for improved system resource efficiency..

**Comment by Xaxxis** [comment]
Hi @rickzal13 thank you for contribute to our java library. 

We have listed the Connection Pooling feature to the next development. But we don't have any ETA for the release. 

Thank you

**Comment by rickzal13** [comment]
Hi @Xaxxis thank you for great response.

We really appreciate if the connection pooling feature to be added in your next release. We really looking forward to it.

Thank you

**Comment by Xaxxis** [comment]
Hi @rickzal13 Midtrans java library has released a new version with Connection Pooling feature ya. Kindly update the library to v2.1.1.

Thank you

**Comment by rickzal13** [comment]
Oke.. Thank You..
