### ISSUE TITLE
How to junit user clicking complete for snap popup and doing payment @ sandbox ?

### ISSUE THREAD

**Issue by albert-kam** [Midtrans/midtrans-java#8]
Dear Java brothers,

The simplistic payment flow in my app:
- User checkouts
- User click on payment
- Server side acquiring token and render html containing snap js api calls
- And the SNAP popups on the browser
- Assuming the user choosed the BCA VA
- The user is shown the steps, which number to transfer, etc
- The user clicks the 'complete' button at the bottom of the popup
- This actually calls my onSuccess callback url
- The server side then queries midtrans for that specific transaction status
- Further notifications will also trigger this code to check for that specific transaction status

I could test the server side acquiring token.
But i'm at lost here on how to test a transaction status, both with pending and done status. 
Ideally i could do these in my junit:
- Simulate the user choosing the payment type
- Simulate the user clicking on the 'complete' button in the test
- Simulate the user having paid
- So that i could get the transaction status and assert the responses

How do i simulate a user clicking the 'complete' button on snap to trigger a transaction having pending or done status @ midtrans sandbox for each payment types that i'm going to support ?

The only approach i can think of right now is to use headless browser automation to junit these. 
Please enlighten me.

Warm regards from Jakarta,
Bert

**Comment by albert-kam** [comment]
Hi again guys, it's okay. I could just mock the midtrans server, hardcoding the responses. Thank youuu.

**Comment by Xaxxis** [comment]
Hi @albert-kam thank you for reaching out to us.

If the question is how to 
- Simulate the user choosing the payment type
- Simulate the user clicking on the 'complete' button in the test
- Simulate the user having paid
- get the transaction status and assert the responses

You can use a headless browser automate. You can use selenium and JUnit to achieve this. Use selenium to simulate user completed payment in Snap, after simulate payment. Assert the result with API status via JUnit. Use the order-id as a parameter from options Snap js `onSuccess` and `onPending` to get status from our API status. 

If the user only chooses the payment type and close the snap page, the transaction status is `Pending`. If the user chooses the payment type, then pay (via [our simulator](https://simulator.sandbox.midtrans.com/assets/index.html)), and close the snap page, the transaction status is `Settlement` (for credit_card is `capture`)


> Hi again guys, it's okay. I could just mock the midtrans server, hardcoding the responses. Thank you

Yes, also the easy way to achieving this with mock our response


If you have any general question, you can reach out to us via email support@midtrans.com

Thank you
