### ISSUE TITLE
Http Notification payload type ?

### ISSUE THREAD

**Issue by albert-kam** [Midtrans/midtrans-java#9]
Hi again !

I am reading https://snap-docs.midtrans.com/#http-s-post-notification for the http notification payload containing the order_id, but it doesnt mention whether it is a json payload, or is it just plain http POST data ?

Thanks,
Bert

**Comment by Xaxxis** [comment]
Hi @albert-kam yes, it's JSON payload, for the details may you can check our tech docs on [how handling the notification](https://docs.midtrans.com/en/after-payment/http-notification)
Here's our [sample controller with springboot](https://github.com/Midtrans/midtrans-java/blob/master/example/src/main/java/com/midtrans/sample/controller/CoreApiController.java#L94-L123)

Thank you

**Comment by albert-kam** [comment]
Ah, thank you very much. Didnt know this documentation exists.
